name: Hypercubed
version: '${project.version}'
main: hypersquare.hypersquare.Hypersquare
api-version: 1.20
commands:
  join:
    description: Join a plot
    usage: /<command> plotID
  dev:
    description: Go to dev on your current plot
    usage: /<command>
  locate:
    description: Find another player
    usage: /<command> player
    aliases: find
  spawn:
    description: Teleports to spawn
    usage: /<command>
    aliases: s