name: Hypersquare
version: '${project.version}'
main: hypersquare.hypersquare.Hypersquare
api-version: 1.20
commands:
  join:
    description: Join a plot
    usage: /join <plotID>
  dev:
    description: Go to dev on your current plot
    usage: /dev
    aliases:
      - code
  locate:
    description: Find another player
    usage: /locate <player>
    aliases:
      - find
  spawn:
    description: Teleports to spawn
    usage: /spawn
    aliases:
      - s
      - leave
      - lobby
  build:
    description: Go to build on your current plot
    usage: /build
  play:
    description: Go to play on your current plot
    usage: /play
  fs:
    description: Set your flightspeed
    usage: /fs <speed>
    aliases:
      - flyspeed
      - flightspeed
  plot:
    description: Manage your plot
    usage: /plot <subcommand>
    aliases:
      - p
  editspawn:
    description: Edit the spawn region
    usage: /editspawn
    aliases:
      - ps
  fly:
    description: Enable flight
    usage: /fly
  dumplots:
    description: deletes all plots
    usage: /dumplots
  giveplot:
    description: Give plots
    usage: /giveplot <player> <type> <amount>
  text:
    description: Gives player a text item
    usage: /text <text>
    aliases:
      - txt
  debug:
    description: Debug code
    usage: /debug

depend:
  - NBTAPI
  - LuckPerms
